version: "3"
services:
  front-app:
    build:
      context: ./front-app
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./front-app:/usr/app
    ports:
      - "4001:8081"
    restart: always

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app
    ports:
      - "4010:4000"
    restart: always

  postgres:
    image: postgres:12.1
    environment:
      POSTGRES_USER: root_user
      POSTGRES_PASSWORD: root_pass
      POSTGRES_DB: db_blog_app
    volumes:
      - postgres_blog_app:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:4.16
    environment:
      PGADMIN_DEFAULT_EMAIL: admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_LISTEN_PORT: 80
    volumes:
      - pgadmin_blog_app:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  postgres_blog_app:
  pgadmin_blog_app:
